export const seedProducts = [
  {
    name: 'NeuroLink Band',
    description: 'Brain-computer interface wristband for controlling smart devices with thoughts',
    price: 899,
    category: 'Wearables',
    image: '/products/neurolink-band.png',
    stock: 15,
    featured: true,
  },
  {
    name: 'HoloDesk Pro',
    description: 'Holographic workspace projector for 3D multi-monitor setup',
    price: 2499,
    category: 'Workspace',
    image: '/products/holodesk-pro.png',
    stock: 8,
    featured: true,
  },
  {
    name: 'QuantumCore CPU',
    description: 'Personal quantum processor for advanced AI computing',
    price: 4999,
    category: 'Computing',
    image: '/products/quantumcore-cpu.png',
    stock: 5,
    featured: true,
  },
  {
    name: 'AirClean Nano',
    description: 'AI-powered air purifier with molecular-level filtration',
    price: 599,
    category: 'Smart Home',
    image: '/products/airclean-nano.png',
    stock: 20,
    featured: false,
  },
  {
    name: 'SmartGlass AR Pro',
    description: 'Augmented reality glasses with AI assistant integration',
    price: 1299,
    category: 'Wearables',
    image: '/products/smartglass-ar-pro.png',
    stock: 12,
    featured: true,
  },
  {
    name: 'BioPod Sleep System',
    description: 'AI sleep optimization pod with biometric monitoring',
    price: 3799,
    category: 'Health Tech',
    image: '/products/biopod-sleep.png',
    stock: 6,
    featured: false,
  },
  {
    name: 'NanoBot Cleaner',
    description: 'Microscopic cleaning robots for home surfaces',
    price: 449,
    category: 'Smart Home',
    image: '/products/nanobot-cleaner.png',
    stock: 25,
    featured: false,
  },
  {
    name: 'PhotonCharge Station',
    description: 'Wireless quantum charging hub for all devices',
    price: 299,
    category: 'Accessories',
    image: '/products/photoncharge-station.png',
    stock: 30,
    featured: false,
  },
];

